import Head from 'next/head'
import Image from 'next/image'
import album from '../assets/album.jpg'
import { IconArrowRight } from '@tabler/icons-react'
import { Avatar, Badge, Button, Card, Center, Col, Container, Grid, Group, Overlay, Space, Stack, Text, Title } from '@mantine/core'
import TrendingCard from '@/components/Card/TrendingCard'
import NewReleaseCard from '@/components/Card/NewReleaseCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>ROYAL.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card h={240} radius={0} sx={{ position: 'relative' }}>
          <Image src={album} alt='' fill style={{ objectFit: 'cover' }} />
          <Overlay
            gradient="linear-gradient(-145deg, rgba(0, 0, 0, 0.95) 0%, rgba(0, 0, 0, 0) 100%)"
            opacity={0.85}
            zIndex={0}
          />
          <div style={{ zIndex: 1, position: 'absolute', color: '#FFF', height: 'inherit' }}>
            <Grid columns={24} justify='end' align='center' sx={{ width: '100vw', height: 'inherit' }}>
              <Col span={12}>
                <Stack spacing='xl'>
                  <div>
                    <Badge color='slate.5'>Single</Badge>
                    <Text weight={600}>CULTURE CODE, ARAYA, RUNN</Text>
                    <Title weight={800}>THE ACT</Title>
                  </div>
                  <Group spacing={40}>
                    <Text weight={500} color='slate.2'>Trading is LIVE</Text>
                    <Button compact variant='outline' color='slate.1'>BUY NOW</Button>
                  </Group>
                </Stack>
              </Col> 
            </Grid>
          </div>
        </Card>
        <Container size={820} py={32}>
          <Title order={4} weight={600} mb={16}>Trending</Title>
          <Grid columns={24} gutter={32}>
            <Col span={12}>
              <TrendingCard />
            </Col>
            <Col span={12}>
              <TrendingCard />
            </Col>
          </Grid>

          <Space h={48} />

          <Title order={4} weight={600} mb={16}>New Release</Title>
          <Grid columns={24} gutter={32}>
            <Col span={12}>
              <NewReleaseCard />
            </Col>
            <Col span={12}>
              <NewReleaseCard />
            </Col>
            <Col span={12}>
              <NewReleaseCard />
            </Col>
            <Col span={12}>
              <NewReleaseCard />
            </Col>
          </Grid>
          <Center my={16}>
            <Button compact variant='subtle' rightIcon={<IconArrowRight size={16} />}>View all</Button>
          </Center>

          <Space h={48} />

          <Title order={4} weight={600} mb={32}>Top Collectors</Title>
          <Grid columns={24}>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl' />
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl'>
                  <Badge>#1</Badge>
                </Avatar>
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl' />
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl' />
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl' />
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
            <Col md={4}>
              <Stack justify='center' align='center' spacing='xs'>
                <Avatar src='https://royal-io.imgix.net/3a153bb6-ecf2-4827-994d-0cfdb02343ab.png' radius='xl' size='xl' />
                <div>
                  <Text weight={500}>Craig</Text>
                  <Text weight='lighter' size='xs'>@C7D</Text>
                </div>
              </Stack>
            </Col>
          </Grid>
          <Center my={16}>
            <Button compact variant='subtle' rightIcon={<IconArrowRight size={16} />}>View all</Button>
          </Center>
        </Container>
      </main>
    </>
  )
}
